export const eventABI = [
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: 'idx', type: 'uint256' },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'startTime',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'deadlineTime',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'endTime',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'helperAddress',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'sToken',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'sTotal',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'creator',
        type: 'address',
      },
      {
        components: [
          { internalType: 'string[]', name: 'data', type: 'string[]' },
          { internalType: 'uint256[]', name: 'odds', type: 'uint256[]' },
        ],
        indexed: false,
        internalType: 'struct EDataTypes.Option',
        name: 'options',
        type: 'tuple',
      },
    ],
    name: 'EventCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'caller',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'eventId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'string',
        name: 'result',
        type: 'string',
      },
    ],
    name: 'EventResultUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'caller',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'eventId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'enum EDataTypes.EventStatus',
        name: 'status',
        type: 'uint8',
      },
    ],
    name: 'EventStatusUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint8', name: 'version', type: 'uint8' },
    ],
    name: 'Initialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_idx', type: 'uint256' },
      { internalType: 'uint256', name: '_startTime', type: 'uint256' },
      { internalType: 'uint256', name: '_deadlineTime', type: 'uint256' },
      { internalType: 'uint256', name: '_endTime', type: 'uint256' },
      { internalType: 'address', name: '_helperAddress', type: 'address' },
      { internalType: 'address', name: '_sToken', type: 'address' },
      { internalType: 'uint256', name: '_sTotal', type: 'uint256' },
      {
        components: [
          { internalType: 'string[]', name: 'data', type: 'string[]' },
          { internalType: 'uint256[]', name: 'odds', type: 'uint256[]' },
        ],
        internalType: 'struct EDataTypes.Option',
        name: '_options',
        type: 'tuple',
      },
    ],
    name: 'createSingleEvent',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'events',
    outputs: [
      { internalType: 'uint256', name: 'startTime', type: 'uint256' },
      { internalType: 'uint256', name: 'deadlineTime', type: 'uint256' },
      { internalType: 'uint256', name: 'endTime', type: 'uint256' },
      { internalType: 'string', name: 'result', type: 'string' },
      {
        internalType: 'enum EDataTypes.EventStatus',
        name: 'status',
        type: 'uint8',
      },
      { internalType: 'address', name: 'helperAddress', type: 'address' },
      { internalType: 'address', name: 'sToken', type: 'address' },
      { internalType: 'uint256', name: 'sTotal', type: 'uint256' },
      { internalType: 'address', name: 'creator', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_eventId', type: 'uint256' }],
    name: 'info',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'startTime', type: 'uint256' },
          { internalType: 'uint256', name: 'deadlineTime', type: 'uint256' },
          { internalType: 'uint256', name: 'endTime', type: 'uint256' },
          { internalType: 'string', name: 'result', type: 'string' },
          {
            internalType: 'enum EDataTypes.EventStatus',
            name: 'status',
            type: 'uint8',
          },
          { internalType: 'address', name: 'helperAddress', type: 'address' },
          { internalType: 'address', name: 'sToken', type: 'address' },
          { internalType: 'uint256', name: 'sTotal', type: 'uint256' },
          { internalType: 'address', name: 'creator', type: 'address' },
          { internalType: 'string[]', name: 'options', type: 'string[]' },
          { internalType: 'uint256[]', name: 'odds', type: 'uint256[]' },
        ],
        internalType: 'struct EDataTypes.Event',
        name: '_event',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_eventId', type: 'uint256' },
      { internalType: 'string', name: '_result', type: 'string' },
    ],
    name: 'updateEventResult',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_eventId', type: 'uint256' },
      { internalType: 'address', name: '_sToken', type: 'address' },
      { internalType: 'uint256', name: '_sTotal', type: 'uint256' },
    ],
    name: 'updateSToken',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
