name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: '404a894f-f163-40b7-8a07-36945d7f6782'
          heroku_app_name: 'efun-be-v2' #Must be unique in Heroku
          heroku_email: 'ngobao2001@gmail.com'
